workflows:
  ios_unsigned_app:
    name: iOS Unsigned App

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Flutter packages
        script: |
          flutter pub get

      - name: Build unsigned iOS app
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/Runner.app
